// Auto-generated by scripts/generate-types.ts
// Do not edit manually

export interface BlogPost {
  id: string;
  status: string;
  user_created?: string;
  date_created?: string;
  user_updated?: string;
  date_updated?: string;
  title?: string;
  content?: string;
  featured_image?: string;
  slug?: string;
  date_published?: string;
  translations: unknown;
}

export interface BlogPostTranslations {
  id: number;
  blog_post_id?: string;
  languages_code?: string;
  status?: string;
  title?: string;
  content?: string;
  slug?: string;
}

export interface Languages {
  code: string;
  name?: string;
  direction?: string;
}

export interface Schema {
  blog_post: BlogPost[];
  blog_post_translations: BlogPostTranslations[];
  languages: Languages[];
}
