import {
  createDirectus,
  rest,
  staticToken,
  readCollections,
  readFields,
} from "@directus/sdk";
import { writeFileSync } from "fs";

const client = createDirectus("http://localhost:8055")
  .with(staticToken(process.env.DIRECTUS_TOKEN!))
  .with(rest());

const TYPE_MAP: Record<string, string> = {
  string: "string",
  text: "string",
  integer: "number",
  bigInteger: "number",
  float: "number",
  decimal: "number",
  boolean: "boolean",
  date: "string",
  dateTime: "string",
  timestamp: "string",
  time: "string",
  json: "Record<string, unknown>",
  csv: "string[]",
  uuid: "string",
  hash: "string",
};

async function generateTypes() {
  const collections = await client.request(readCollections());
  const fields = await client.request(readFields());

  const userCollections = collections.filter(
    (c) => !c.collection.startsWith("directus_"),
  );

  let output = `// Auto-generated by scripts/generate-types.ts\n`;
  output += `// Do not edit manually\n\n`;

  const schemaEntries: string[] = [];

  for (const collection of userCollections) {
    const collectionFields = fields.filter(
      (f) => f.collection === collection.collection,
    );

    let interfaceStr = `export interface ${toPascalCase(collection.collection)} {\n`;

    for (const field of collectionFields) {
      const tsType = TYPE_MAP[field.type] ?? "unknown";
      const optional = field.schema?.is_nullable ? "?" : "";
      interfaceStr += `  ${field.field}${optional}: ${tsType};\n`;
    }

    interfaceStr += `}\n`;
    output += interfaceStr + "\n";

    schemaEntries.push(
      `  ${collection.collection}: ${toPascalCase(collection.collection)}[];`,
    );
  }

  // Generate the root Schema type for the SDK
  output += `export interface Schema {\n`;
  output += schemaEntries.join("\n");
  output += `\n}\n`;

  writeFileSync("./src/types/directus.d.ts", output);
  console.log("✅ Directus types generated at src/types/directus.d.ts");
}

function toPascalCase(str: string): string {
  return str
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

generateTypes().catch(console.error);
